INSERT INTO mojabaza.movie (movie_description, movie_title) VALUES ('Film o zabawnym ogrze i jego osle', 'Shrek');
INSERT INTO mojabaza.movie (movie_description, movie_title) VALUES ('Opis', 'Terminator');
INSERT INTO mojabaza.movie (movie_description, movie_title) VALUES ('Opis', 'Terminator 2');
INSERT INTO mojabaza.movie (movie_description, movie_title) VALUES ('Opis', 'Shrek 2');
INSERT INTO mojabaza.movie (movie_description, movie_title) VALUES ('Opis', 'Shrek 3');
INSERT INTO mojabaza.movie (movie_description, movie_title) VALUES ('Opis', 'Szybcy i Wsciekli');
INSERT INTO mojabaza.movie (movie_description, movie_title) VALUES ('Opis', 'Za szybcy, za wsciekli');
INSERT INTO mojabaza.movie (movie_description, movie_title) VALUES ('Opis', 'Avatar');
INSERT INTO mojabaza.movie (movie_description, movie_title) VALUES ('Opis', 'Dzien Swira');
INSERT INTO mojabaza.movie (movie_description, movie_title) VALUES ('Opis', 'Chlopaki nie placza');